### ISSUE TITLE
How do I get predictions for STL model other than in benchmarked dataset?

### ISSUE THREAD

**Issue by VK1995** [PeizhiShi/SsdNet#3]
Hi @PeizhiShi,

I have tested pretrained SsdNet model with the use of multi-feature dataset, appreciate your work!

I changed 'test_ssdnet' function in test.py so that I could get pred array for any other model.

Snippet of changed 'test_ssdnet()'

```python
def test_ssdnet(sidx, metric = cal_detection_performance):
    
    net = load_pretrained_model()
    
    predictions = np.zeros(24)
    # truelabels = np.zeros(24)
    # truepositives = np.zeros(24)
    
    with torch.no_grad():
        with open(os.devnull, 'w') as devnull:
            for filename in Path('data/MulSet/set' + str(sidx)+ '/').glob('*.STL'):
                filename = str(filename).replace('.STL','')
                
                # pred, trul, tp = metric(get_predicted_label(filename, net), get_gt_label(filename+'.csv'))
                
                pred_labels = get_predicted_label(filename, net)
                print('pred_labels: ', pred_labels[:, 6])
                pred = get_lvec(pred_labels[:, 6])
                
                predictions += pred
                # truelabels += trul
                # truepositives += tp
                
                print(filename)
                    
                # print(trul)
                print(pred)
                # print(tp)
               
```

I got following error for any model other than your benchmarked multi-feature dataset

```shell 
(ssdnet-env) (py_3.6.8) F:\desktop\teamrepo\Vishal\FeatureExtraction\github_projects\SsdNet>python test.py
F:\desktop\teamrepo\Vishal\FeatureExtraction\github_projects\SsdNet\ssdnet-env\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: [WinError 126] The specified module could not be found
  warn(f"Failed to load image Python extension: {e}")
Loading weights into state dict...
Finished!
test.py:179: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ..\torch\csrc\utils\tensor_new.cpp:201.)
  images = torch.tensor(images).permute(0, 3, 1, 2).float()
Traceback (most recent call last):
  File "test.py", line 462, in <module>
    test_ssdnet(data_group,cal_detection_performance) #feature recognition
  File "test.py", line 432, in test_ssdnet
    pred_labels = get_predicted_label(filename, net)
  File "test.py", line 185, in get_predicted_label
    out = net(images, 'test')
  File "F:\desktop\teamrepo\Vishal\FeatureExtraction\github_projects\SsdNet\ssdnet-env\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\desktop\teamrepo\Vishal\FeatureExtraction\github_projects\SsdNet\ssdnet-env\lib\site-packages\torch\nn\parallel\data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "F:\desktop\teamrepo\Vishal\FeatureExtraction\github_projects\SsdNet\ssdnet-env\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\desktop\teamrepo\Vishal\FeatureExtraction\github_projects\SsdNet\ssd.py", line 148, in forward
    self.priors.type(type(x.data))                  # default boxes # Non-static forward method
  File "F:\desktop\teamrepo\Vishal\FeatureExtraction\github_projects\SsdNet\layers\functions\detection.py", line 41, in forward
    self.num_classes).transpose(2, 1)
RuntimeError:  shape '[6, 8190, 25]' is invalid for input of size 19656000
```

As ssdnet model results are highly precise, can you tell me how I should get 'predictions' for any other STL model.

Please let me know if I am doing anything wrong.

Thank you!

**Comment by PeizhiShi** [comment]
Hi, did you convert the CAD model into 64X64X64 grids as suggested in our paper?

**Comment by VK1995** [comment]
Hi @PeizhiShi ,

Thanks for the reply, it solved the above issue.

I converted the CAD model into 64x64x64 grid and got predicted labels for my own STL model as shown below

![image](https://user-images.githubusercontent.com/84552224/149622249-fb95d1b3-e862-4b06-9eb0-b9762114284f.png)

Predicted labels are, 
1. Triangular through slot
2. Rectangular through slot
3. Rectangular through step
4. Chamfer
5. Round

But expecting 'Through hole'

Is there anything I am doing wrong?

Again same question, how should I test any other model?

Thanks!

**Comment by PeizhiShi** [comment]
Which voxelization tool did you choose? Did you use the binvox (https://www.patrickmin.com/binvox/) mentioned in our research paper? One thing that needs to be noticed is that binvox sometimes does not work as expected on some operating systems (e.g. ubuntu). After converting a *.STL model into *.binvox file, it is better to use the viewvox (https://www.patrickmin.com/viewvox/) provided on binvox website to visualize your *.binvox file to check whether the conversion is done successfully. In addition, z-buffer based carving is also employed to speed up the converting process.

Once the conversation is done successfully,  you could visualize the predicted features based on your own binvox model by running 'python visualize.py' (you need to change the [file id](https://github.com/PeizhiShi/SsdNet/blob/79d0e565f2255217cb309863d68969e33ad6008e/visualize.py#L328) in this python file to visualize your own model).

The code in this github repository is only a simple prototype which shows our view-based idea for intersecting feature recognition. To simplify the comparison, our model in this repository was trained to recognise 24 types of machining features on a **cubic** stock. These 24 features are negative features which are predefined in the FeatureNet paper. In other words, the provided ML model could not be utilised to predict machining features which have not been seen during training (e.g. positive features on **non-cubic stock**). If you want to recognise features on non-cubic stock as shown in your example, modifications to the code are required. If you want to recognise other feature types, you need to collect data with these feature types, and train the ML models by yourself. In addition, this approach cannot handle free-form features (or free-form stocks) as stated in our paper.

**Comment by VK1995** [comment]
Does it solved by tuning hyperparameters & Keeping the same model of yours?
